baseURL = 'https://easteregghunt.netlify.app'
languageCode = 'en-us'
title = 'Easter Egg Hunt ğŸ‡'
theme = "paper"
copyright = "Copyright Â© 2008â€“2019, Steve Francia and the lee.so; all rights reserved."

[menu]

  [[menu.main]]
    identifier = "websitecarbon"
    name = ""
    url = "https://www.websitecarbon.com/website/easteregghunt-netlify-app/"
    weight = 10
